name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarScanner CLI
        shell: cmd
        run: |
          sonar-scanner.bat ^
            -Dsonar.projectKey=Avi123Avi_Promtx_Test_abaeb944-6d84-4a33-b914-42a52dee4f72 ^
            -Dsonar.sources=. ^
            -Dsonar.host.url=${{ SONAR_HOST_URL }} ^
            -Dsonar.login=${{ SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
