name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate Sonar analysis

      - name: Run SonarScanner CLI
        shell: cmd
        run: |
          sonar-scanner.bat `
            -Dsonar.projectKey=Avi123Avi_Promtx_Test_abaeb944-6d84-4a33-b914-42a52dee4f72
            -Dsonar.sources=. `
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} `
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Optional: Uncomment this step to enforce Quality Gate (can fail the build)
      # - name: Check Quality Gate status
      #   uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
